config/routes.rb
PahthsProject::Application.routes.draw do

  root to: 'static_pages#home'

  match '/about',   to: 'static_pages#about'

  resources :users do
    member do
      get :manage_pahths
    end
  end

  match '/signup',  to: 'users#new'

  resource :user_sessions, only: [:new, :create, :destroy]
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  resources :pahths do
    member do
      get :build_new
      post :build_create
    end
  end

  resources :p_steps

end

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  %div.error_explanation
    %div.alert.alert-error
      The form contains
      = pluralize(object.errors.count, "error")
    %ul
      -object.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_p_steps_feed_item.html.haml
%article.steps-feed
  %hgroup
    %h1= link_to p_steps_feed_item.title, p_steps_feed_item
  %p= p_steps_feed_item.content

app/views/shared/_pahths_feed_item.html.haml
%article.pahths-feed
  %figure
    = link_to image_tag("buda1.jpg"), pahths_feed_item
  %hgroup
    %h1
      = link_to "#{pahths_feed_item.title} Path", pahths_feed_item
    %h1
      %i.grey-1.font-13
        by
        = link_to pahths_feed_item.user.name, pahths_feed_item.user, :class => "grey-1"
    %h2= pahths_feed_item.pahth_tipo
  %p= pahths_feed_item.description

app/views/shared/_teaching_pahths_feed_item.html.haml
%li
  %span.content.center=  link_to teaching_pahths_feed_item.title, build_new_pahth_path(teaching_pahths_feed_item),
  class: "btn"
  - if current_user?(teaching_pahths_feed_item.user)
    %div.center= link_to "delete", teaching_pahths_feed_item, method: :delete,
    data: { confirm: "You sure?" }, title: teaching_pahths_feed_item.content

app/views/shared/_to_dos_feed_item.html.haml
%li= link_to to_dos_feed_item.title, to_dos_feed_item

app/views/shared/_user_new.html.haml
= provide(:title, 'Sign up')

= form_for :user, :url => { :controller => "users",:action => "create" } do |f|

  %fieldset

    %legend Join Us



    %section

      %article
        = f.label :name
        = f.text_field :name

      %article
        = f.label :email
        = f.text_field :email

      %article
        = f.label :password
        = f.password_field :password

      %article
        = f.label :password_confirmation, "Confirmation"
        = f.password_field :password_confirmation

      %article
        = f.submit "Create my account", class: "btn-submit"