config/routes.rb
PahthsProject::Application.routes.draw do

  root to: 'static_pages#home'

  match '/about',   to: 'static_pages#about'

  resources :users do
    member do
      get :manage_pahths
    end
  end

  match '/signup',  to: 'users#new'

  resource :user_sessions, only: [:new, :create, :destroy]
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  resources :pahths do
    member do
      get :build_new
      post :build_create
    end
  end

  resources :p_steps

end

app/models/pahth.rb
class Pahth < ActiveRecord::Base
  attr_accessible :title, :description, :pahth_tipo, :content

  belongs_to :user

  has_many :step_pahths, dependent: :destroy
  has_many :p_steps, :through => :step_pahths


  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 50 }
  validates :pahth_tipo, presence: true, length: { maximum: 50 }
  validates :content, length: { maximum: 1000 }

  default_scope order: 'pahths.created_at DESC'


end

app/controllers/pahths_controller.rb
class PahthsController < ApplicationController
  before_filter :signed_in_user
  before_filter :correct_user,   only: [:destroy, :build]

  def new
    @pahth = Pahth.new
  end


  def create
    @pahth = current_user.pahths.build(params[:pahth])
    if @pahth.save
      flash[:success] = "Pahth created!"
      redirect_to manage_pahths_user_path(current_user)
    else
      render 'new'
    end
  end


  def show
    @pahth = Pahth.find(params[:id])
    @p_steps_feed_items = current_pahth.p_steps
  end

# Build a new Path by adding steps on the go
  def build_new
    @pahth = Pahth.find(params[:id])
    @p_step = PStep.new
    @p_steps_feed_items = current_pahth.p_steps
    store_location
  end

# Create the new steps and add to the path on the go
  def build_create
    @p_step = current_user.p_steps.build(params[:p_step])
    if @p_step.save
      @step_pahth = StepPahth.new(:pahth_id => current_pahth.id, :p_step_id => @p_step.id,:times_taken => 0)
      if @step_pahth.save
        @p_steps_feed_items = current_pahth.p_steps
        flash[:success] = "Step created!"
        redirect_to build_new_pahth_path(current_pahth.id)
      else
        @p_steps_feed_items = current_pahth.p_steps
        flash[:notice] = "Step was created but not added to Path!"
        render 'pahths/build_new'
      end
    else
      @p_steps_feed_items = current_pahth.p_steps
      flash[:notice] = "Step could not be created!"
      render 'pahths/build_new'
    end
  end

  def destroy
    @pahth.destroy
    redirect_to manage_pahths_user_path(current_user)
  end

  private

  def correct_user
    @pahth = current_user.pahths.find_by_id(params[:id])
    redirect_to root_url if @pahth.nil?
  end


end

app/helpers/pahths_helper.rb
module PahthsHelper

  def learning_types_array
    ['Book', 'Movie', 'MOOC', 'Article', 'Lecture', "Tutorial video"  ]
  end

end

app/views/pahths/build.html.haml
-# Build a Path by adding steps

= provide(:title, "#{@pahth.title} | Build")

%div.container

  %section.center.beauty-blue
    %h1
      = @pahth.title
      %h2
        = @pahth.pahth_tipo
        %h4.center


  %div.half-split-left.semi-tall.top-margin.styled-select
    = form_for([@pahth, @p_step]) do |f|

      = render 'shared/error_messages', object: f.object

      = f.label :title
      = f.text_field :title

      = f.label :learning_style
      = f.select :type_learning, learning_types_array, :prompt => 'Select One'


      = f.label :description
      = f.text_area :content, :rows => 5

      = f.submit "Create Step", class: "btn btn-large btn-primary"

  %div.half-split-right.semi-tall.top-margin
    %h3 Steps Feed
    = render 'shared/p_steps_feed'

app/views/pahths/build_new.html.haml
-# Build a Path by adding steps

= provide(:title, "#{@pahth.title} | Build")

%div.container

  %h1= "#{@pahth.title} Path"

  %div.half-split-left.semi-tall.top-margin.styled-select
    %h3 Add Steps
    = form_for @p_step, :url => build_create_pahth_path(@pahth.id) do |f|

      = render 'shared/error_messages', object: f.object

      = f.label :title
      = f.text_field :title

      = f.label :knowledge_category
      = f.text_field :category_knowledge

      = f.label :learning_style
      = f.select :type_learning, learning_types_array, :prompt => 'Select One'


      = f.label :description
      = f.text_area :content, :rows => 5

      = f.submit "Create Step", class: "btn btn-large btn-primary"

  %div.half-split-right.semi-tall.top-margin
    %h3 Steps Feed
    = render 'shared/p_steps_feed'

app/views/pahths/new.html.haml
= provide(:title, 'Create Pahth')



= form_for(@pahth) do |f|

  %fieldset.grid_4

    %legend Create Path

    = render 'shared/error_messages', object: f.object

    %section

      %article
        = f.label :title
        = f.text_field :title

      %article
        = f.label :type
        = f.text_field :pahth_tipo

      %article
        = f.label :description
        = f.text_area :description, :rows => 5

      %article= f.submit "Create Path", class: "btn btn-large btn-primary", :class => "btn-submit"

%section.grid_2.push_4.to-dos= to_do_list

app/views/pahths/show.html.haml
= provide(:title, @pahth.title)

%div.container

  %section.center.beauty-blue
    %h1
      = @pahth.title
      %h2
        = @pahth.pahth_tipo
        %h4.center


  %div.half-split-left.semi-tall.top-margin
    %h1 To Dos

  %div.half-split-right.semi-tall.top-margin
    %h3 Steps Feed
    - if @p_steps_feed_items.any?
      = render partial: 'shared/p_steps_feed_item', collection: @p_steps_feed_items