config/routes.rb
PahthsProject::Application.routes.draw do

  root to: 'static_pages#home'

  match '/about',   to: 'static_pages#about'

  resources :users do
    member do
      get :manage_pahths
    end
  end

  match '/signup',  to: 'users#new'

  resource :user_sessions, only: [:new, :create, :destroy]
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  resources :pahths do
    member do
      get :build_new
      post :build_create
    end
  end

  resources :p_steps

end

app/views/layouts/_footer.html.haml
%ul
  %li= link_to "About", about_path
  %li= link_to "Impact", '#'

app/views/layouts/_header.html.haml
%header

  %div.container_12

    %div.grid_2#logo
      %a{:href => root_path}<
        %span> learn
        %span.blue-2 paths

    %div.grid_3.push_7
      %nav.nav-header
        %ul
          - if current_user
            %li= link_to "Edit Profile", edit_user_path(current_user.id)
            %li= link_to "Log Out", :logout
          - else
            %li= link_to "Log In", :login

app/views/layouts/_nav_list.html.haml
%div.nav-menu
  %ul
    = nav_link "Home", root_path, "sub-menu border-hover"
    %li.sub-menu Learn
    = nav_link "My Paths", '#', "border-hover"
    = nav_link "My Steps", '#', "border-hover"
    %li.sub-menu Teach
    = nav_link "Create Path", new_pahth_path, "border-hover"
    = nav_link "Teaching Paths", manage_pahths_user_path(current_user),"border-hover"
    = nav_link "Teaching Steps", new_p_step_path, "border-hover"

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
   <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
   <![endif]-->

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= full_title(yield(:title))
    %link(rel="shortcut icon" href="/favicon.ico/")
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

    = render 'layouts/shim'

  %body

    = render 'layouts/header'

    %div.wrapper

      %div.container_12
        %div.grid_9.push_2
          - flash.each do |key, value|
            %div{:class=> "alert alert-#{key}"}= value

      %div.container_12
        - if current_user
          %div.grid_2.omega
            =render 'layouts/nav_list'

          = yield

        - else
          = yield

      %footer.container_12
        = render 'layouts/footer'

      %div.container_12
        %div.grid_6.push_3.control-development
          = debug(params) if Rails.env.development?